"""newv2

Revision ID: 1404094bff36
Revises: ab4381e2d846
Create Date: 2023-01-15 02:34:49.356988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1404094bff36'
down_revision = 'ab4381e2d846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
