"""newv4

Revision ID: 538231434ad8
Revises: 8c8dd869ec0d
Create Date: 2023-01-15 14:19:42.319233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538231434ad8'
down_revision = '8c8dd869ec0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
