"""newv3

Revision ID: 8c8dd869ec0d
Revises: 1404094bff36
Create Date: 2023-01-15 02:36:38.582863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8dd869ec0d'
down_revision = '1404094bff36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
