version: '3.3'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart:
      always
    env_file:
      app/.env
    ports:
      - 5432:5432
  
  redis_db:
    container_name: redis_db
    image: redis:latest
    depends_on:
      - postgres_db
    restart: always
    ports:
      - 6379:6379