version: '3.3'

services:

  redis_db:
    container_name: redis_db
    image: redis:latest
    restart: always
    env_file:
      - app/.env
    ports:
      - 6379:6379

  postgres_db_test:
    container_name: postgres_db_test
    image: postgres:15.1-alpine
    restart:
      on-failure
    env_file:
      app/.env
    ports:
      - 5432:5432
    depends_on:
      - redis_db
