version: '3.3'

services: 
  web:
    container_name: web
    build:
      context: app/
      dockerfile: Dockerfile
    command:
      bash -c "alembic upgrade head && python3 run_server.py"
    restart:
      always
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
 
  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart:
      always
    env_file:
      app/.env
    expose:
      - 5432
 