version: '3.3'

services: 
  web:
    container_name: web
    build:
      context: app/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
 
  postgres_db:
    container_name: postgres_db
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: restaurant_menu
      POSTGRES_PASSWORD: gera
      POSTGRES_USER: gera
    ports:
      - 5432